name: "Examples (smoke test)"
on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]

jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{env.PYTHON_VERSION}}
          cache: 'poetry'
      - name: Install
        run: poetry install
      - name: Run examples
        run: make examples
