name: 'Examples'
on: push
jobs:
  examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: pip install -r requirements.txt
    - name: Install log10 package
      run: pip install .
    - name: Run examples
      run: make examples
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}

